title: Théo Yeter # your name (or website title) here
logo: "" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>"I am Théo Yeter, a passionate data analyst with over 3 years of experience in the field1. I have a solid background as a Data Analyst and Account Executive, where I worked on a variety of projects from data extraction and analysis to setting up acquisition strategies and marketing campaigns. I am proficient in several tools and software, including Python, SQL, Power BI, Looker Studio, and Excel. I recently completed a Data Analytics bootcamp at Le Wagon in Bordeaux. You can check out some of my projects on this portfolio."<br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/th%C3%A9o-yeter/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
